name: Example Workflow

on:
  push:
    branches:
      - feature/testing10

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Print inputs
        run: |
          echo "Username: ${{ github.event.inputs.git-username }}"
          echo "Repository: ${{ github.event.inputs.repo }}"
